name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install SFDX
      run: |
        echo do stuff....
    - name: Run Tests
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run Tests
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
